steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$_SERVICE_NAME",
        "--build-arg _PROJECT_ID=${_PROJECT_ID}",
        "--build-arg _TRIGGER_ID=${_TRIGGER_ID}",
        "--build-arg _BRANCH_NAME=${_BRANCH_NAME}",
        ".",
      ]
substitutions:
  _SERVICE_NAME: TODO
  _PROJECT_ID: TODO
  _TRIGGER_ID: TODO
  _BRANCH_NAME: TODO
images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME
